// CRUD
  // Create
  export const CREATE_STUDENT_REQUEST = 'CREATE_STUDENT_REQUEST'
  export const CREATE_STUDENT_SUCCESS = 'CREATE_STUDENT_SUCCESS'
  export const CREATE_STUDENT_FAILURE = 'CREATE_STUDENT_FAILURE'
  // Read
  export const READ_STUDENT_REQUEST = 'READ_STUDENT_REQUEST'
  export const READ_STUDENT_SUCCESS = 'READ_STUDENT_SUCCESS'
  export const READ_STUDENT_FAILURE = 'READ_STUDENT_FAILURE'
  // Update
  export const UPDATE_STUDENT_REQUEST = 'UPDATE_STUDENT_REQUEST'
  export const UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS'
  export const UPDATE_STUDENT_FAILURE = 'UPDATE_STUDENT_FAILURE'
  // Delete
  export const DELETE_STUDENT_REQUEST = 'DELETE_STUDENT_REQUEST'
  export const DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS'
  export const DELETE_STUDENT_FAILURE = 'DELETE_STUDENT_FAILURE'